version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: main_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecuritypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - main_net

  web:
    image: julially/t1_task
    container_name: web_app
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_NAME: main_database
      DATABASE_USER: admin
      DATABASE_PASSWORD: supersecuritypassword
    ports:
      - 7000:6000
    depends_on:
      - postgres_db
    networks:
      - main_net

volumes:
  postgres_data:

networks:
  main_net:
    driver: bridge
  
